### ISSUE TITLE
figure out sorting issue for textplot_xray and docnames

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#404]
This is `test-plots.R` lines 68-75.

@adamobeng I was not sure what the behaviour should be, can you check now that we've rewritten `kwic()`? Thanks!

**Comment by adamobeng** [comment]
The tests all pass for me: https://travis-ci.org/kbenoit/quanteda/builds/189245420. What's the problem?

**Comment by kbenoit** [comment]
The tests pass for me too, but with a commit I made this morning, Appveyor (Windows CI) is saying that one of the tests fails. I have just been trying to build the system on Windows 7 and 10 (in Parallels) but cannot get around this annoying issue, when I try to build it:

```
> devtools::install_github("kbenoit/quanteda")
Downloading GitHub repo kbenoit/quanteda@master
from URL https://api.github.com/repos/kbenoit/quanteda/zipball/master
Installing quanteda
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/kbenoit/AppData/Local/Temp/Rtmp6RRWoe/devtools18b0c436d2e/kbenoit-quanteda-3a1bb04" --library="\\Mac/Home/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'quanteda' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.2/include" -DNDEBUG    -I"\\Mac/Home/Documents/R/win-library/3.3/Rcpp/include" -I"\\Mac/Home/Documents/R/win-library/3.3/RcppParallel/include" -I"\\Mac/Home/Documents/R/win-library/3.3/RcppArmadillo/include" -I"d:/Compiler/gcc-4.9.3/local330/include"  -DRCPP_PARALLEL_USE_TBB=1   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:4:27: fatal error: RcppArmadillo.h: No such file or directory
 #include <RcppArmadillo.h>
                           ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="quanteda.dll" OBJECTS="RcppExports.o dist_parallel.o fcm.o sequences.o tokens.o tokens_detect_mt.o tokens_lookup_mt.o tokens_ngrams_mt.o tokens_replace_mt.o tokens_select_mt.o utility.o wordfish.o"' had status 2
ERROR: compilation failed for package 'quanteda'
* removing '\\Mac/Home/Documents/R/win-library/3.3/quanteda'
```

**Comment by adamobeng** [comment]
Just a guess, but it looks like you're compiling a 32 bit version on a 64 bit system. Are the 32 bit libraries installed?

**Comment by adamobeng** [comment]
Just a guess, but it looks like you're compiling a 32 bit version on a 64 bit system. Are the 32 bit libraries installed?

**Comment by kbenoit** [comment]
We're solving the problems of my Windows build separately, but the issue here is `test-plots.R` [lines 49-77](https://github.com/kbenoit/quanteda/blob/master/tests/testthat/test-plots.R#L49-L77). These don't pass and are currently commented out. I thought you could fix the code to make them pass once uncommented.
